
services:
  activemq:
    image: apache/activemq-artemis:latest-alpine
    container_name: activemq
    ports:
      - "61616:61616"   # Broker port (apps connect here)
      - "8161:8161"     # Web console
    environment:
      ARTEMIS_USER: admin
      ARTEMIS_PASSWORD: admin
    volumes:
      - activemq-data:/var/lib/artemis-instance

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: trainer_workload
    volumes:
      - mongodb-data:/data/db

  gym-service:
    build: ./spring-gym-core
    container_name: gym-service
    ports:
      - "8080:8080"
    environment:
      SPRING_ARTEMIS_BROKER-URL: tcp://activemq:61616
      SPRING_ARTEMIS_USER: admin
      SPRING_ARTEMIS_PASSWORD: admin
      EUREKA_CLIENT_ENABLED: "false"
    depends_on:
      - activemq

  trainer-workload-service:
    build: ./trainer-workload-service
    container_name: trainer-workload-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongodb:27017/trainer_workload?authSource=admin
      SPRING_ARTEMIS_BROKER-URL: tcp://activemq:61616
      SPRING_ARTEMIS_USER: admin
      SPRING_ARTEMIS_PASSWORD: admin
      EUREKA_CLIENT_ENABLED: "false"
    depends_on:
      - activemq
      - mongodb

volumes:
  activemq-data:
  mongodb-data:
